.PHONY: init_project

python_setup_mac:
	python -m venv .venv
	source .venv/bin/activate
	python -m pip install --upgrade pip
	python -m pip install -r requirements.txt

python_setup_win:
	python -m venv .venv
	.venv\Scripts\activate
	python -m pip install --upgrade pip
	python -m pip install -r requirements.txt