version: 2

sources:
  - name: airbnb # Source name
    schema: raw  # Schema name
    tables:
      - name: listings # reference to the table name
        identifier: raw_listings # Table name

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}