steps:
# If training model in cloud and save model in GCS
# Assume Storage location of model: `gs://dev-aiml-model/models/sentiment`
# Download the model file in GCS to embed it into the image
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '${_MODEL_GCS_PATH}', './models']
    id: 'download-model'
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '.']
    waitFor: ['download-model']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

images:
  - '${_IMAGE_NAME}'

# Substitution variables for flexibility
substitutions:
  _MODEL_GCS_PATH: 'gs://dev-aiml-model/models/sentiment'
  _IMAGE_NAME: 'asia-southeast1-docker.pkg.dev/ext-pinetree-dw/dev-aiml-model/sentiment-fast-api'
